spring.application.name=demo
#management.endpoints.web.exposure.include=health,info
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
#security
#management.endpoints.web.exposure.exclude=health,info
info.app.name= App
info.app.description= My first app!
info.app.version=1.0.0


